# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            blog | singuerinc
tagline:          'ningún derecho reservado'
description:      'Nada importante aquí, sólo código que no quiero olvidar.'
url:              http://blog.singuerinc.com

author:
  name:           'Nahuel Scotti'
  url:            https://twitter.com/singuerinc
  github:         https://github.com/singuerinc

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/singuerinc/lanyon
